chain/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import TemplateView

app_name = 'chain'

urlpatterns = [

    # Basic Things For User
    url(r'^$', login_required(views.index) , name='index'),
    url(r'^sensors/$', login_required(views.sensors) , name='sensors'),
    url(r'^sensor/(?P<pk>[0-9]+)/$', login_required(views.sensor) , name='sensor'),
    url(r'^datas/$', login_required(views.datas) , name='datas'),
    url(r'^data/(?P<pk>[0-9]+)/$', login_required(views.data) , name='data'),

    # test -- Will Remove after Completing Project
    url(r'^test/$', login_required(views.test) , name='test'),

    #for User To getting Permission for our website
    url(r'^login/$', views.login_user , name='login'),
    url(r'^logout/$', login_required(views.logout_user) , name='logout'),
    url(r'^register/$', views.Register_User.as_view() , name='register'),

    # for managing node
    url(r'^AddNode/$', login_required(views.new_node) , name='AddNode'),
    url(r'^UpdateNode/(?P<pk>[0-9]+)/$', login_required(views.UpdateNode.as_view()) , name='UpdateNode'),
    url(r'^(?P<pk>[0-9]+)/DeleteNode/$', login_required(views.DeleteNode.as_view()) , name='DeleteNode'),

    # For user
    url(r'^AddUser/$', login_required(views.AddUser) , name='AddUser'),
    url(r'^UpdateUser/(?P<pk>[0-9]+)/$', login_required(views.UpdateUser.as_view()) , name='UpdateUser'),

    # for managing Sensor
    url(r'^AddSensor/$', login_required(views.new_sensor) , name='AddSensor'),
    url(r'^UpdateSensor/(?P<pk>[0-9]+)/$', login_required(views.UpdateSensor.as_view()) , name='UpdateSensor'),
    url(r'^(?P<pk>[0-9]+)/DeleteSensor/$', login_required(views.DeleteSensor.as_view()) , name='DeleteSensor'),

    # for managing data
    url(r'^AddData/$', login_required(views.AddData.as_view()) , name='AddData'),
    url(r'^(?P<pk>[0-9]+)/DeleteData/$', login_required(views.DeleteData.as_view()) , name='DeleteData'),

]

project1/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from chain import views
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import TemplateView

urlpatterns = [

    # For Admin
    url(r'^admin/', admin.site.urls),

    # for Root
    url(r'^$', login_required(views.index) , name='login'),

    # For App
    url(r'^chain/', include('chain.urls' , namespace="chain")),

    # for overwriting login_required decorators
    url(r'^accounts/login/$', views.login_user , name='login'),
]

chain/models.py
from django.db import models
import datetime
from django.contrib.auth.models import Permission, User
from django.core.urlresolvers import reverse
from django.forms import ModelForm
from itertools import chain

class Profile(models.Model):
    first_name = models.CharField(max_length = 40)
    last_name = models.CharField(max_length = 40)
    owner = models.ForeignKey(User,on_delete = models.CASCADE)
    about = models.CharField(max_length = 400, blank=True)
    doc = models.DateTimeField(blank=True, default=datetime.datetime.now)
    image = models.CharField(max_length = 400, blank = True, default = "http://www.hit4hit.org/img/login/user-icon-6.png")
    def get_absolute_url(self):
        return reverse('chain:index')
    def __str__(self):
        return self.first_name

# For Gateway --
class Gateway(models.Model):
    name = models.CharField(max_length = 40)
    description = models.CharField(max_length = 400, blank=True)
    doc = models.DateTimeField(blank=True, default=datetime.datetime.now)
    def __str__(self):
        return self.name

# for Node --
class Node(models.Model):
    gateway_name = models.ForeignKey(Gateway,on_delete = models.CASCADE)
    name = models.CharField(max_length = 40)
    image = models.CharField(max_length = 400 , default = "https://d3s5r33r268y59.cloudfront.net/97443/products/thumbs/2016-08-30T16:15:27.419Z-IMG-20160823-WA0018.jpg.855x570_q85_pad_rcrop.jpg")
    owner = models.ForeignKey(User,on_delete = models.CASCADE)
    description = models.CharField(max_length = 400, blank=True)
    doc = models.DateTimeField(blank=True, default=datetime.datetime.now)
    def get_absolute_url(self):
        return reverse(request , 'chain/test.html')
    def __str__(self):
    #    str1 = str(self.owner) + ' -- ' + self.name
        return self.name

# For Sensor --
class Sensor(models.Model):
    node_name = models.ForeignKey(Node,on_delete = models.CASCADE)
    name = models.CharField(max_length = 40)
    description = models.CharField(max_length = 400, blank=True)
    image = models.CharField(max_length = 400 , default = "https://upload.wikimedia.org/wikipedia/commons/0/09/CCD_Image_sensor.jpg")
    doc = models.DateTimeField(blank=True, default=datetime.datetime.now)
    def get_absolute_url(self):
        return reverse('chain:index')
    def __str__(self):
        return self.name

# For Data --
class Data(models.Model):
    sensor_name = models.ForeignKey(Sensor,on_delete = models.CASCADE)
    data = models.CharField(max_length = 40)
    description = models.CharField(max_length = 400, blank=True)
    doc = models.DateTimeField(blank=True, default=datetime.datetime.now)
    def get_absolute_url(self):
        return reverse('chain:index')
    def __str__(self):
        return self.data

# For Node Form
class NodeForm(ModelForm):
    class Meta:
        model = Node
        exclude = ('owner', 'doc', 'image',)

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ('owner', 'doc', 'image',)

# For Sensor to set that in form you can get only User nodes.
class SensorForm(ModelForm):
    class Meta:
        model = Sensor
        exclude = ('doc', 'image',)
    def __init__(self, var=None, *args, **kwargs):
        super(SensorForm, self).__init__(*args, **kwargs)
        self.fields['node_name'].queryset = Node.objects.filter(owner=var)

chain/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Node

# For overwriting Userfor for registering User.
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

chain/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import *
from django.contrib.auth import authenticate,login, logout
from .forms import UserForm
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import CreateView,UpdateView, DeleteView
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.template import RequestContext
from django.shortcuts import render_to_response

# For adding a user Profile
def AddUser(request):
    if request.method == "POST":
        form = ProfileForm(request.POST or None )
        if form.is_valid():
            temp_node = form.save(commit=False)
            temp_node.owner = request.user
            temp_node.save()
            mynodes = Node.objects.filter(owner=request.user)
            return render(request, 'chain/index.html' , { 'mynodes' : mynodes})
        else:
            form = ProfileForm(initial={'owner': request.user})
            return render(request, 'chain/profile_form.html', {'form': form})
    else:
        form = ProfileForm()
        return render(request, 'chain/profile_form.html', {'form': form})

# For updating the User
class UpdateUser(UpdateView):
        model= Profile
        fields = ['first_name','last_name','about', 'image']


# It's the homepage
def index(request):
        mynodes = Node.objects.filter(owner=request.user)
        return render(request, 'chain/index.html' , { 'mynodes' : mynodes})

# It's for testing some new things
def test(request):
        return render(request, 'chain/base1.html' )

# it's for registering new user
class Register_User(View):
    form_class = UserForm
    template_name = 'chain/reg.html'

    def get(self,request):
        form = self.form_class(None)
        return render (request,self.template_name , {'form' :form })

    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            # normalised data_set
            username = form.cleaned_data ['username']
            password = form.cleaned_data ['password']
            user.set_password(password)
            user.save()
            user = authenticate(username=username,password=password)
            if user is not None:

                if user.is_active:
                    login(request,user)
                    return redirect ('chain:index')
        return render(request, self.template_name , {'form': form})

# For user login
def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                mynodes = Node.objects.filter(owner=request.user)
                return render(request, 'chain/index.html', {'mynodes' : mynodes})
            else:
                return render(request, 'chain/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'chain/login.html', {'error_message': 'Invalid login'})
    return render(request, 'chain/login.html')

# For logout user
def logout_user(request):
        logout(request)
        return render(request, 'chain/login.html')

# For updating node
class UpdateNode(UpdateView):
        model= Node
        fields = ['gateway_name','name','description','image']

# For Deleting Node
class DeleteNode(DeleteView):
        model= Node
        success_url = reverse_lazy('chain:index')

# For Updating Sensor
class UpdateSensor(UpdateView):
        model= Sensor
        fields = ['name' ,'description','image']

# For Deleting Sensor
class DeleteSensor(DeleteView):
        model= Sensor
        success_url = reverse_lazy('chain:index')

# To find all Sensors att One place
def sensors(request):
        mynodes = Node.objects.filter(owner=request.user)
        return render(request, 'chain/sensors.html' , { 'mynodes' : mynodes})

# To Find all sensors attached to a Node
def sensor(request,pk):
        mynodes = Node.objects.filter(pk=pk)
        return render(request, 'chain/sensor.html' , { 'mynodes' : mynodes})

# To find data of a sensor
def data(request,pk):
        mysensors = Sensor.objects.filter(pk=pk)
        return render(request, 'chain/data.html' , { 'mysensors' : mysensors})

# To find all data From all sensors
def datas(request):
        mynodes = Node.objects.filter(owner=request.user)
        return render(request, 'chain/datas.html' , { 'mynodes' : mynodes})

# For adding data Manualy -- Remove later for automatically updating data
class AddData(CreateView):
        model= Data
        fields = ['sensor_name','data' ]

# For deleting data
class DeleteData(DeleteView):
        model= Data
        success_url = reverse_lazy('chain:index')

# Adding a New Node
def new_node(request):
    if request.method == "POST":
        form = NodeForm(request.POST or None )
        if form.is_valid():
            temp_node = form.save(commit=False)
            temp_node.owner = request.user
            temp_node.save()
            mynodes = Node.objects.filter(owner=request.user)
            return render(request, 'chain/index.html' , { 'mynodes' : mynodes})
        else:
            form = NodeForm(initial={'owner': request.user})
            return render(request, 'chain/node_form.html', {'form': form})
    else:
        form = NodeForm()
        return render(request, 'chain/node_form.html', {'form': form})

# For Adding A new sensor
def new_sensor(request):
    if request.method == "POST":
        form = SensorForm(request.user, request.POST or None )
        if form.is_valid():
            temp_sensor = form.save(commit=False)
            # For checking if someone is try to add sensor to someone elses node.
            if temp_sensor.node_name.owner == request.user:
                temp_sensor.save()
                mynodes = Node.objects.filter(owner=request.user)
                return render(request, 'chain/index.html' , { 'mynodes' : mynodes})
            else:
                form = SensorForm( request.user)
                return render(request, 'chain/sensor_form.html', {'form': form ,'error_message': 'Not your node'})
        else:
            form = SensorForm( request.user)
            return render(request, 'chain/sensor_form.html', {'form': form})
    else:
        form = SensorForm( request.user)
        return render(request, 'chain/sensor_form.html', {'form': form})

chain/templates/chain/AddNode.html
<div class="" id="Left_Side">
<div id="adduser">
<br>
{% for field in form  %}
    <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
              <span class="text-danger small"> {{field.errors}} </span>
          </div>
          <label class="control-label col-sm-2">  {{field.label_tag}} </label>
          <div class="col-sm-11"> {{field}} </div>
    </div>
{% endfor %}
</div>
</div>

chain/templates/chain/base.html
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title  %} Kristnam {% endblock  %}</title>

    {% load staticfiles %}

    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js">
    <link rel="javascript" type="text/js" href= "{% static '/chain/style.js' %}">
    <link rel="stylesheet" type="text/css" href= "{% static '/chain/style.css' %}">
  </head>


<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">

<body class="home">
    <div class="container-fluid display-table">
        <div class="row display-table-row">
            <div class="col-md-2 col-sm-1 hidden-xs display-table-cell v-align box" id="navigation">

                <div class="navi">
                    <ul>
                        <li class=""><a href="{% url 'chain:index' %}"><i class="fa fa-home" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Home</span></a></li>
                        <li><a href="{% url 'chain:sensors' %}"><i class="fa fa-tasks" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Sensor</span></a></li>
                        <li><a href="{% url 'chain:datas' %}"><i class="fa fa-bar-chart" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Data</span></a></li>
                        <li><a href="{% url 'chain:AddNode' %}"><i class="fa fa-user" aria-hidden="true"></i><span class="hidden-xs hidden-sm">AddNode</span></a></li>
                        <li><a href="{% url 'chain:AddSensor' %}"><i class="fa fa-calendar" aria-hidden="true"></i><span class="hidden-xs hidden-sm">AddSensor</span></a></li>
                        <li><a href="{% url 'chain:AddData' %}"><i class="fa fa-cog" aria-hidden="true"></i><span class="hidden-xs hidden-sm">AddData</span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10 col-sm-11 display-table-cell v-align">
                <!--<button type="button" class="slide-toggle">Slide Toggle</button> -->
                <div class="row">
                    <header>
                        <div class="col-md-7">
                            <nav class="navbar-default pull-left">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="offcanvas" data-target="#side-menu" aria-expanded="false">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                </div>
                            </nav>


                        </div>
                        <div class="col-md-5">
                            <div class="header-rightside">
                                <ul class="list-inline header-top pull-right">
                                    <li><a href="https://mail.google.com/mail/u/0/#inbox"><i class="fa fa-envelope" aria-hidden="true"></i></a></li>

                                    <li class="dropdown">
                                        <a href="{% url 'chain:logout' %}" class="dropdown-toggle" data-toggle="dropdown"> <strong>Logout</strong>
                                            </a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <div class="navbar-content">
                                                    <span>JS Krishna</span>
                                                    <p class="text-muted small">
                                                        me@jskrishna.com
                                                    </p>
                                                    <div class="divider">
                                                    </div>
                                                    <a href="{% url 'chain:AddData' %}" class="view btn-sm active">View Profile</a>
                                                </div>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </header>
                </div>

                <div class="user-dashboard">
                    <div class="row">
                        <div class="col-md-5 col-sm-5 col-xs-12 gutter">

                          {% block body %}

                          {% endblock  %}

                        </div>
                        <div class="col-md-7 col-sm-7 col-xs-12 gutter">

                          {% block body_right %}

                          {% endblock  %}

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>



    <!-- Modal
    In case If we need a search bar
    <div class="search hidden-xs hidden-sm">
        <input type="text" placeholder="Search" id="search">
    </div>


  -->


</body>
</html>

chain/templates/chain/base1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title  %}Kristnam{% endblock  %}</title>

    {% load staticfiles %}

    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js">
    <link rel="stylesheet" type="text/css" href= "{% static '/chain/style.css' %}">
  </head>


  <body>
          <nav class="navbar navbar-inverse">
                    <div class="collapse navbar-collapse" id="#topNavbar">
                            <ul class="nav navbar-nav">
                                    <li class="">
                                          <a href="{% url 'chain:index' %}">
                                            <span class = "glyphicon glyphicon-home" area-hidden = "true" > </span> &nbsp;Home
                                          </a>
                                    </li>
                                    <li class="">
                                          <a href="{% url 'chain:sensors' %}">
                                            <span class = "glyphicon glyphicon-cloud" area-hidden = "true" > </span> &nbsp; Sensors
                                          </a>
                                    </li>

                                    <li class="">
                                          <a href="{% url 'chain:datas' %}">
                                            <span class = "glyphicon glyphicon-cloud" area-hidden = "true" > </span> &nbsp; Data
                                          </a>
                                    </li>


                             </ul>

                             <ul class="nav navbar-nav navbar-right">

                                   <li class="">
                                         <a href="{% url 'chain:AddNode' %}">
                                           <span class = "glyphicon glyphicon-plus" area-hidden = "true" > </span> &nbsp; Add Nodes
                                         </a>
                                   </li>


                                   <li class="">
                                         <a href="{% url 'chain:AddSensor' %}">
                                           <span class = "glyphicon glyphicon-plus" area-hidden = "true" > </span> &nbsp; Add Sensor
                                         </a>
                                   </li>

                                   <li class="">
                                         <a href="{% url 'chain:AddData' %}">
                                           <span class = "glyphicon glyphicon-plus" area-hidden = "true" > </span> &nbsp; Add Data
                                         </a>
                                   </li>

                                   <li class="">
                                         <a href="{% url 'chain:logout' %}">
                                           <span class = "glyphicon glyphicon-off" area-hidden = "true" > </span> &nbsp; Logout
                                         </a>
                                   </li>
                             </ul>

                    </div>
          </nav>


          {% block body  %}

          {% endblock  %}

  </body>
</html>

chain/templates/chain/base_login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title  %}Login Page{% endblock  %}</title>

    {% load staticfiles %}

    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js">
    <link rel="stylesheet" type="text/css" href= "{% static '/chain/style.css' %}">
  </head>


  <body>

          <nav class="navbar navbar-inverse">
                    <div class="collapse navbar-collapse" id="#topNavbar">
                            <ul class="nav navbar-nav">
                                    <li class="">
                                          <a href="{% url 'chain:login' %}">
                                            <span class = "glyphicon glyphicon-home" area-hidden = "true" > </span> &nbsp;Login
                                          </a>
                                    </li>

                                    <li class="">
                                          <a href="{% url 'chain:register' %}">
                                            <span class = "glyphicon glyphicon-home" area-hidden = "true" > </span> &nbsp;Register
                                          </a>
                                    </li>


                            </ul>



                    </div>
          </nav>


          {% block body  %}

          {% endblock  %}
          {% block body_right %}

          <div class="" id="Right_Side">

            <h3> Here are soemething that can help you </h3>
              <p>
                  We made a help page to help you throughout.
                  We will gonna put some suggestion for you here.
              </p>
          </div>




          {% endblock body_right %}

  </body>
</html>

chain/templates/chain/datas.html
{% extends "chain/base.html" %}

{% block title %}Data{% endblock %}

{% block body %}

<div class="" id="Left_Side">

        {% if mynodes %}

              {% for nodes in mynodes %}

                    {% if nodes.sensor_set.all %}
                        {% for  sensor in nodes.sensor_set.all %}

                              {% for  data1 in sensor.data_set.all %}
                                <ul class="list-group">
                                  <li class="list-group-item">
                                    {{data1.data}}
                                    &nbsp       <a href ="{% url 'chain:DeleteData'  data1.id %}"  class="btn btn-primary btn-sm" role="button"> Delete Data </a>

                                  </li>
                                </ul>

                              {% endfor %}



                        {% endfor %}

                    {%endif%}

              {% endfor %}

        {% else %}

        <h3>
          You have not any node. <br> <br>
          <a href="{%url "chain:AddNode"%}">Click</a> Here to add a Node.
        </h3>


        {% endif %}


</div>

{% endblock %}

{% block body_right %}

<div class="" id="Right_Side">

  <h3> Here are soemething that can help you </h3>
    <p>
        We made a help page to help you throughout.
        We will gonna put some suggestion for you here.
    </p>
</div>




{% endblock body_right %}

chain/templates/chain/reg.html
{% extends "chain/base_login.html" %}

{% block title  %} Create Account {% endblock  %}

{% block body  %}

<div class="container-fluid">

    <form class="form-horizontal", action="", method="post" ,enctype="multipart/form-data">
          {% csrf_token %}
          {% include "chain/AddUser.html" %}
          <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                    <br>
                    <button type="submit" class="btn btn-success"> Create Account </button>
                     <br> <br>


                        Already have an account? <a href="{% url 'chain:login' %}">Click here</a> to log in.



              </div>



          </div>


    </form>

</div>

{% endblock  %}


{% block body_right %}

<div class="" id="Right_Side">

  <h3> Here are soemething that can help you </h3>
    <p>
        We made a help page to help you throughout.
        We will gonna put some suggestion for you here.
    </p>
</div>




{% endblock body_right %}

chain/templates/chain/sensor.html
{% extends "chain/base.html" %}

{% block title %}Sensor{% endblock %}

{% block body %}

<div class="" id="Left_Side">

              {% for nodes in mynodes %}

                    {% if nodes.sensor_set.all %}
                      <h4>Here is your sensors in node {{nodes}} Sir <br> <br></h4>
                        {% for  node in nodes.sensor_set.all %}
                          <ul class="list-group">
                            <li class="list-group-item">
                              &nbsp       <a href ="{% url 'chain:data'  node.id %}"> {{node.name}}  </a>
                              &nbsp       <a href ="{% url 'chain:UpdateSensor'  node.id %}" class="btn btn-primary btn-sm" role="button"> Update Sensor </a>
                              &nbsp       <a href ="{% url 'chain:DeleteSensor'  node.id %}"  class="btn btn-primary btn-sm" role="button"> Delete Sensor </a>

                            </li>
                          </ul>


                        {% endfor %}

                    {% else %}

                      <h4>You had not added any sensor to node {{nodes}}</h4>

                    {%endif%}

              {% endfor %}
</div>

{% endblock %}

  <!-- Node Details -->

{% block body_right %}

{% for node in mynodes %}

<div class="albums-container container-fluid">

    <div class="row"> <br> <br>

                <div class="col-sm-6 col-lg-5">
                    <div class="thumbnail">
                          <a href="{% url 'chain:UpdateNode'  node.id %}">
                                <img src="{{node.image}}" height="200" width="200"/> <br>
                               </a>

                        <div class="caption">
                            <h2>{{ node.name }}  </h2>
                            <p>
                              {{node.description}}

                            </p>
                            <!-- View Details -->
                            <a href="{% url 'chain:UpdateNode'  node.id %}" class="btn btn-primary btn-sm" role="button">Update</a>

                            <!-- Delete Album -->
                            <form action="{% url 'chain:DeleteNode' node.id %}" method="post" style="display: inline">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ contacts.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->

                        </div>
                    </div>
                </div>

    </div>


</div>



{% endfor %}

{% endblock  %}

chain/templates/chain/sensors.html
{% extends "chain/base.html" %}

{% block title %}Sensor{% endblock %}

{% block body %}

<div class="" id="Left_Side">

{% if mynodes %}
      {% for nodes in  mynodes %}
          {% if nodes.sensor_set.all %}
            <h3> Node -- {{nodes.name}}</h3>
                {% for  node in nodes.sensor_set.all %}
                  <ul class="list-group">
                    <li class="list-group-item">
                      &nbsp       <a href ="{% url 'chain:data'  node.id %}"> {{node.name}}  </a>
                      &nbsp       <a href ="{% url 'chain:UpdateSensor'  node.id %}" class="btn btn-primary btn-sm" role="button"> Update Sensor </a>
                      &nbsp       <a href ="{% url 'chain:DeleteSensor'  node.id %}"  class="btn btn-primary btn-sm" role="button"> Delete Sensor </a>

                    </li>
                  </ul>

                {% endfor %}

          {%endif%}

      {% endfor %}

{% else %}

  <h3>
    You have not any node. <br> <br>
    <a href="{%url "chain:AddNode"%}">Click</a> Here to add a Node.
  </h3>

{% endif %}

</div>


{% endblock %}



{% block body_right %}

<div class="" id="Right_Side">

  <h3> Here are soemething that can help you </h3>
    <p>
        We made a help page to help you throughout.
        We will gonna put some suggestion for you here.
    </p>
</div>




{% endblock body_right %}